Fix#3
kdada/tinygo pull request #4
Opened 2016-12-06 10:00 UTC by narrowizard

bug issue #3 fixed.

2016-12-06 11:14 UTC, kdada requested changes

2016-12-06 11:14 UTC, kdada commented on session/memory.go
> +			this.rwm.RUnlock()
RUnlock should unlock after `var ss, ok = this.sessions[sessionId]`. Don't call RUnlock twice.

2016-12-07 10:07 UTC, kdada commented
Please squash your commits

@narrowizard

2016-12-07 11:46 UTC, narrowizard commented
commits rebased.
@kdada

2016-12-08 01:47 UTC, kdada commented
LGTM

2016-12-08 01:47 UTC, kdada approved these changes

2016-12-08 01:47 UTC, merged